version: '3'
services:
    nginx:
        container_name: nginx
        build: ./nginx
        image: profile_page/nginx:v1
        restart: always
        network_mode: "host"
        ports:
          - "80:80"
        volumes:
          - ./profile_page:/srv/profile_page
          - ./log:/var/log/nginx
          - ./profile_page/static/:/static
        depends_on:
          - django
    django:
        container_name: django
        build: ./profile_page
        image: profile_page/django:v1
        restart: always
        command: uwsgi --ini uwsgi.ini
        volumes:
          - ./profile_page:/srv/profile_page
          - ./log:/var/log/uwsgi
    mysql:
      # 사용할 이미지
      image: mysql
      # 컨테이너 이름 설정
      container_name: test-mysql
      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
      ports:
        - "3306:3306"
      # -e 옵션
      environment:
        MYSQL_DATABASE: "django"
        MYSQL_USER: "root"
        MYSQL_PASSWORD: "abc12345"
        MYSQL_ROOT_PASSWORD: "admin123"
      # 명령어 실행 (한글 인코딩 관련)
      command:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      volumes:
        # -v 옵션 (다렉토리 마운트 설정)
        - /home/ubuntu/mysql/data:/var/lib/mysql